### PR TITLE
[WIP] Working version with some updates.

### PR DESCRIPTION
**Pull request by chrispiccaro18**
Added the following functionality:
- Quit at anytime during the game by inputting 9. Also updated the standard message "Select a move" with "Select a move or 9 to quit".
- Prevents players from choosing numbers that are out-of-bounds (except for 9, which quits, see above).
- Prevents players from choosing an already occupied space.
- Calling a tie (cat's game) based on the maximum # of moves.
- Added 3 missing win conditions.
- Print out the winning board.

I still want to add an option to play again.

-CP

### CODE REVIEW

**Comment by chrispiccaro18** [comment]
Noticed some bugs but I'm too fried to try and fix them now:
- Two out-of-bounds moves in a row will give a syntax error. I'm assuming because it doesn't check again.
- Similarly, two illegal moves in a row will just overwrite the occupied space.

**Comment by chrispiccaro18** [comment]
Fixed the bugs in the last comment, but I don't fully understand why for the out-of-bounds.

**Comment by chrispiccaro18** [comment]
As per the commit message, forgot to check the 8th space as an occupied space. Fixed that now and also added another Walter line.

**Comment by sts10** [comment]
Cool! Some notes: 

## My code does in fact check those 3 winning conditions 

They are checked for with these three lines:

```golang
for _, v := range b[0:2] { sums[7] += v }
for _, v := range b[3:5] { sums[6] += v }
for _, v := range b[6:8] { sums[5] += v }
```

Admittedly it's not very intuitive-- I used `for` loops for these 3 cases cuz the board places all happen to be in a row. I sort of touched on this [here](https://sts10.github.io/2017/11/18/trying-go-and-rust.html#a-note-on-looping-in-go).

## Prevent out-of-bounds moves seems overly complex

You're a bit fast-and-loose with terms like "illegal" and "out-of-bounds" moves. The keyword `continue` might help clean up this section as well. What about something like:

```golang
for {
  currentMove = askForPlay()
  // Quit with '9'
  if currentMove == 9 {
    return
  }
  if spaceIsOccupied(currentMove, board) {
    fmt.Println("This space is occupied. Try again.")
    continue
  }
  // Prevent out-of-bounds moves
  if currentMove > 9 {
    fmt.Println("Please enter a number under 10.")
    continue
  }
}
```

Then go write a separate `spaceIsOccupied` function that returns `true` if space is occupied and `false` if not. 

Alternatively we could build this check into the existing `executePlayerMove`, which is nice because then it'd be even harder to accidentally fill a space twice. This is what I ended up doing in [my Rust implementation](https://github.com/sts10/rusty-tac/blob/master/src/main.rs#L89).

Lastly, it might also be nice if we could take the two `for` loops (the one on your line 11 and your line 22) and combine them into one?

**Comment by sts10** [comment]
Also, in general you want to create one Pull Request per bug fix or new feature. That way the maintainer of the project (me in this case) can, if desired, merge some changes but not all of them. I _think_ the best way to do this is to create different Git **branches** for each feature/pull request.

**Comment by chrispiccaro18** [comment]
Thanks, Sam!

# The straight across win conditions
I wasn't able to get a confirmed win with these three lines: 
```go
for _, v := range b[0:2] { sums[7] += v }
for _, v := range b[3:5] { sums[6] += v }
for _, v := range b[6:8] { sums[5] += v }
```
screen shot 2019-01-22 at 10 23 37 am
Are they working for you?
# Out-of-bounds Moves
Ah, `continue` would be much better.
Ya, I think putting it in `executePlayerMove` would be the best call instead of a new function.
I'll try and combine the two `for` loops.
# Pull Requests
Ok, I'll try the branching method and see how that works.

**Comment by sts10** [comment]
> I wasn't able to get a confirmed win with these three lines:

Huh! If they're not working then yeah, my code must be wrong. I must not have tested it well. 

Feel free to delete my bogus three lines in your PR.

**Comment by sts10** [comment]
Closing this, as Chris was nice enough to break up these PRs in to small pieces.

**Pull request closed without merging**
